name: Test
favicon: null
layout_spectrum: 0.746
typography_spectrum: 0.76932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d2d0'
    - '#8fa2b2'
    - '#120e0d'
    - '#383232'
    - '#846e56'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
