name: Test
favicon: null
layout_spectrum: 0.01435291045345366
typography_spectrum: 0.8252891884185374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.44207333656959236
  lightness: 0.5071248298045248
  saturation: 0.9855107495095581
  rhythmicContrast: 0.6722812515217811
purpose: []
